#+TITLE: Seminario de M칠todos Anal칤ticos de la Empresa
#+AUTHOR: Prof. Alfredo Garbuno I침igo
#+EMAIL:  agarbuno@itam.mx
#+DATE: ~Oto침o, 2022~
#+STARTUP: showall
:REVEAL_PROPERTIES:
#+LANGUAGE: es
#+OPTIONS: num:nil toc:nil 
#+OPTIONS: reveal_slide_number:nil 
#+OPTIONS: reveal_history:t reveal_fragmentinurl:t
#+OPTIONS: reveal_mousewheel:t reveal_inter_presentation_links:t
#+OPTIONS: reveal_width:1600 reveal_height:900
#+OPTIONS: timestamp:nil

#+REVEAL_THEME: night
#+REVEAL_MARGIN: .2
#+REVEAL_TRANS: slide
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="SMAE">
#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_VERSION: 4

#+REVEAL_SLIDE_NUMBER: t
#+REVEAL_PLUGINS: (notes search)
#+REVEAL_EXTRA_CSS: .css/mods.css

#+bibliography: references.bib
#+cite_export: csl
:END:



* Objetivo
:PROPERTIES:
:CUSTOM_ID: objetivo
:END:
Redondear las habilidades de los y las estudiantes e identificar 치reas
de oportunidad de la ciencia de datos en relaci칩n a problem치ticas
sociales, gubernamentales, empresariales, medio ambientales, entre otras
que requieren del an치lisis de grandes vol칰menes de datos para
resolverse.

* Din치mica
:PROPERTIES:
:CUSTOM_ID: din치mica
:END:
Pl치ticas y/o talleres de actualizaci칩n, temas en la frontera, desarrollo
de t칠cnicas o habilidades gerenciales, de negociaci칩n, de toma de
decisiones. Principalmente casos documentados de 칠xito impartidas por
investigadoras e investigadores, practicantes o compa침칤as en ciencia de
datos.

La asistencia a las exposiciones es obligatoria para las personas
inscritas en el seminario.

* Calificaci칩n
:PROPERTIES:
:CUSTOM_ID: calificaci칩n
:END:
| Ensayos y/o ejercicios (4) | Participaci칩n |
|----------------------------+---------------|
| 70 %                       | 30%           |

#+REVEAL: split
De todas las pl치ticas o talleres que se dar치n elegir 4 para realizar 4
entregas. Las entregas son ensayos de extensi칩n entre 800 y 1000
palabras y/o ejercicios que se den.

#+REVEAL: split
游녤 las 4 que elijan deben estar repartidas a lo largo del semestre, no
se aceptar치n entregas que 칰nicamente sean de la 칰ltima semana de octubre
y las del mes de noviembre, por ejemplo.

#+REVEAL: split
Podr칤an entregar por ejemplo 3 ensayos y 1 ejercicios, s칩lo 4 ensayos o
cualquier combinaci칩n que resulte en cuatro entregas en total.

Adem치s, durante las pl치ticas y/o talleres deben participar con preguntas
o contar experiencias relacionadas con los temas tratados que generen
discusiones.

#+REVEAL: split
游녤 as칤 como con las entregas, deben juntar en todo el semestre m칤nimo
tres participaciones y deben ser repartidas. Una por ejemplo en el mes
de agosto, otra en el mes de septiembre y finalmente en el mes de
noviembre, o bien alguna otra combinaci칩n que ustedes decidan. Con cada
participaci칩n obtienen 10% y como m치ximo obtendr치n 30%.

* 쮺uando, d칩nde, formato de mis entregas?
:PROPERTIES:
:CUSTOM_ID: cuando-d칩nde-formato-de-mis-entregas
:END:
La fecha m치xima de las entregas es dos semanas una vez se imparte la pl치tica o
el taller.

En la ~organizaci칩n de Github~ la cual est치 integrada con ~Github Classroom~ se
suben sus entregas.

Los documentos que se revisar치n ser치n en formato ~pdf~. 

* Sobre lo que nunca deben realizar
:PROPERTIES:
:CUSTOM_ID: sobre-lo-que-nunca-deben-realizar
:END:
Copiar en un examen/tarea/trabajo/entrega pues se pondr치 cero en el
mismo. Si vuelve a repetirse la situaci칩n se le notificar치 a direcci칩n
escolar para realizar la anotaci칩n correspondiente en su expediente.

* Sobre lo que siempre deben realizar
:PROPERTIES:
:CUSTOM_ID: sobre-lo-que-siempre-deben-realizar
:END:
Documentar sus referencias, fuentes, colaboraciones y material que
utilizan para resolver sus ex치menes, pr치cticas o proyectos.

* Agenda y organizaci칩n de Github
:PROPERTIES:
:CUSTOM_ID: agenda-y-organizaci칩n-de-github
:END:
La encuentran en [[https://github.com/ITAM-DS/smae/tree/fall-2022/agenda.org][fall-2022]]. 
